Repository leighlars/intention-timer, pull requests merged in 2020-05, with the labels that each got.

#1 Folder set-up
  assets/exercise-active.svg
  assets/exercise.svg
  assets/meditate-active.svg
  assets/meditate.svg
  assets/study-active.svg
  assets/study.svg
  assets/warning.svg
  main.js
  src/activity.js
  src/main.js
Labels: documentation

#3 Add Wireframes Folder
  README.md
  wireframes/Screen Shot 2020-05-26 at 5.40.52 PM.png
  wireframes/Screen Shot 2020-05-26 at 5.41.55 PM.png
  wireframes/Screen Shot 2020-05-26 at 5.43.07 PM.png
Labels: documentation

#4 Base html structure
  index.html
Labels: enhancement

#5 Add font-link and media query tag to html file.
  index.html
  styles.css
Labels: enhancement

#6 Start Styling The Main Body
  styles.css
Labels: enhancement

#7 Feature/add header styling
  index.html
  styles.css
Labels: enhancement

#8 Add styling to past activities section in empty state.
  styles.css
Labels: enhancement

#9 Features/css main body
  index.html
  styles.css
Labels: enhancement

#10 Add Normalize Tag
  index.html
Labels: enhancement

#11 Add page header and header element responsiveness.
  styles.css
Labels: enhancement

#13 Buttons and Main Section
  styles.css
Labels: enhancement

#12 Add margin to main section.
  styles.css
Labels: enhancement

#14 Move section header out of activities section and adjust margins, add box shadow.
  index.html
  styles.css
Labels: enhancement

#15 Form Layout
  index.html
  styles.css
Labels: enhancement

#17 Form Resize
  styles.css
Labels: enhancement

#16 Add styling for h4 element
  styles.css
Labels: enhancement

#18 Add responsiveness to activities and edit margins
  index.html
  styles.css
Labels: enhancement

#20 Feature/polishing css
  styles.css
Labels: enhancement

#19 Define activity class
  src/activity.js
Labels: enhancement

#21 Add spacing on section headers, left border on past sections
  index.html
  styles.css
Labels: documentation

#22 Add script tags
  index.html
Labels: enhancement

#23 Add containers to sections and polish html.
  index.html
Labels: enhancement

#24 Add height to header and adjust page-header styling.
  styles.css
Labels: enhancement

#25 Add styling to new activities view and section header. Main is now to flex.
  styles.css
Labels: enhancement

#26 Add flex display and adjust font size
  styles.css
Labels: enhancement

#28 Update display to flex and add min-sec-area styling.
  styles.css
Labels: enhancement

#29 Adjust styling on start activity button
  styles.css
Labels: enhancement

#30 Remove two in css and add past-header styling.
  styles.css
Labels: enhancement

#31 Start mobile view setup
  styles.css
Labels: enhancement

#32 Continue mobile view for sections
  styles.css
Labels: enhancement

#33 Feature/add mobile view
  styles.css
Labels: enhancement

#34 Add mobile view for past-activities-section and past-header.
  styles.css
Labels: enhancement

#36 Query Selectors, Event Listeners, and Functions
  index.html
  src/main.js
  styles.css
Labels: bug, enhancement

#37 Add input refinement and error divs.
  index.html
Labels: enhancement

#38 Add button error styling
  styles.css
Labels: enhancement

#39 Error messages, Classes, and Refactoring
  src/main.js
Labels: enhancement

#40 Refactored HTML & CSS
  index.html
  styles.css
Labels: enhancement

#41 Renaming
  index.html
  src/activity.js
  src/main.js
  styles.css
Labels: enhancement

#42 Feature/timer view build attempt
  index.html
  src/main.js
  styles.css
Labels: enhancement
