Repository leighlars/intention-timer, pull requests merged in 2020-06, with the labels that each got.

#43 Feature/js functionality
  src/main.js
Labels: enhancement

#44 Feature/add hidden class
  index.html
  src/main.js
  styles.css
Labels: enhancement

#45 Name and CSS polishing
  index.html
  src/main.js
  styles.css
Labels: enhancement

#46 Add dynamicism user description on timer
  index.html
  src/main.js
Labels: enhancement

#47 Feature/readme
  README.md
  index.html
  readme-images/desktop-view.png
  readme-images/mobile-view.png
Labels: documentation

#48 Add timer change and color change for timer button
  index.html
  src/main.js
  styles.css
Labels: enhancement

#49 feature/Countdown start
  src/activity.js
  src/main.js
  styles.css
Labels: enhancement

#50 It2/cleanup
  index.html
  src/main.js
  styles.css
Labels: enhancement

#51 Add 0 to seconds and make button work
  src/activity.js
  src/main.js
Labels: enhancement

#52 Tweak form size
  styles.css
Labels: enhancement

#53 Tiny changes css, rename func noMultipleStarts in both js files
  src/activity.js
  src/main.js
  styles.css
Labels: enhancement

#54 Feature/complete messages
  src/activity.js
  src/main.js
  styles.css
Labels: enhancement

#55 Feature/log activity button
  index.html
  src/activity.js
  src/main.js
  styles.css
Labels: enhancement

#56 Refactor main.js
  src/main.js
Labels: enhancement

#58 Feature/add card js
  index.html
  src/main.js
Labels: enhancement

#59 Tweak activateButton() and disableCategoryButtons() with resp HTML/CSS
  index.html
  src/main.js
  src/trial-run.js
  styles.css
Labels: enhancement

#60 Add cards to DOM
  index.html
  src/activity.js
  src/main.js
  styles.css
Labels: enhancement

#62 It4/display cards
  src/main.js
  styles.css
Labels: enhancement

#63 Add zero before seconds on timer load
  src/main.js
Labels: enhancement

#64 Feature/update readme
  README.md
  readme-images/Desktop-New-Activity-View-Firefox.png
  readme-images/Desktop-New-Activity-View-Safari.png
Labels: documentation

#65 Delete wireframe folder and add top margin to article in mobile view
  index.html
  styles.css
  wireframes/Screen Shot 2020-05-26 at 5.40.52 PM.png
  wireframes/Screen Shot 2020-05-26 at 5.41.55 PM.png
  wireframes/Screen Shot 2020-05-26 at 5.43.07 PM.png
Labels: enhancement

#66 Update README with new videos and correct header inner text.
  README.md
  index.html
  readme-images/Chrome-Desktop-New Activity View.png
  readme-images/Desktop-New-Activity-View-Firefox.png
  readme-images/Desktop-New-Activity-View-Safari.png
  readme-images/Firefox-Desktop-New Activity view.png
  readme-images/Safari-Desktop-New Activity view.png
  readme-images/desktop-new-activity-view.png
  readme-images/desktop-view.png
  readme-images/mobile-new-activity.png
  readme-images/mobile-view.png
  styles.css
Labels: documentation, enhancement

#67 Remove for loop in retrieveStorage (redundancy)
  src/main.js
Labels: enhancement
